### ISSUE TITLE
No fields have a DatabaseField annotation in class javafx.beans.property.ObjectProperty

### ISSUE THREAD

**Issue by PhiSD** [j256/ormlite-core#106]
Hey guys,

I've an issue, when I create a new model. I try to add a foreign field of the ObjectProperty class. 

    @DatabaseTable(tableName = "Server")
    public class Server {

    @DatabaseField(generatedId = true)
    private long id;

    @DatabaseField(canBeNull = false)
    private int port;

    @DatabaseField(columnName = "name", canBeNull = false, persisterClass = SimpleStringPropertyPresister.class)
    private StringProperty nameProperty;

    @DatabaseField(canBeNull = false)
    private boolean isStandard;

    @DatabaseField(foreign = true, foreignAutoRefresh = true, foreignAutoCreate = true, canBeNull = false, persisterClass = SimpleObjectPropertyPresister.class)
    private ObjectProperty<Installation> installation;

But if I start the programm, this error occurs.

`Exception in thread "main" java.lang.IllegalArgumentException: No fields have a DatabaseField annotation in class javafx.beans.property.ObjectProperty
	at com.j256.ormlite.table.DatabaseTableConfig.extractFieldTypes(DatabaseTableConfig.java:215)
	at com.j256.ormlite.table.DatabaseTableConfig.fromClass(DatabaseTableConfig.java:146)
	at com.j256.ormlite.table.TableInfo.<init>(TableInfo.java:53)
	at com.j256.ormlite.dao.BaseDaoImpl.initialize(BaseDaoImpl.java:151)
	at com.j256.ormlite.dao.BaseDaoImpl.<init>(BaseDaoImpl.java:128)
	at com.j256.ormlite.dao.BaseDaoImpl.<init>(BaseDaoImpl.java:107)
	at com.j256.ormlite.dao.BaseDaoImpl$4.<init>(BaseDaoImpl.java:907)
	at com.j256.ormlite.dao.BaseDaoImpl.createDao(BaseDaoImpl.java:907)
	at com.j256.ormlite.dao.DaoManager.createDao(DaoManager.java:70)
	at com.j256.ormlite.field.FieldType.configDaoInformation(FieldType.java:297)
	at com.j256.ormlite.dao.BaseDaoImpl.initialize(BaseDaoImpl.java:201)
	at com.j256.ormlite.dao.BaseDaoImpl.<init>(BaseDaoImpl.java:128)
	at com.j256.ormlite.dao.BaseDaoImpl.<init>(BaseDaoImpl.java:107)
	at com.j256.ormlite.dao.BaseDaoImpl$4.<init>(BaseDaoImpl.java:907)
	at com.j256.ormlite.dao.BaseDaoImpl.createDao(BaseDaoImpl.java:907)
	at com.j256.ormlite.dao.DaoManager.createDao(DaoManager.java:70)`

Thank you for your help!

**Comment by Kcorab** [comment]
It's clear. Read the exception message and look at your `ObjectProperty` class.
There should be any member variable with an `@DatabaseField(...)` annotation; preferably an id field. ORMLite have to know that the foreign object is an entity.
