### ISSUE TITLE
Inserting BigDecimal with custom precision and scale

### ISSUE THREAD

**Issue by ruXlab** [j256/ormlite-core#107]
I was trying to insert values which have `BigDecimal` type in java into mysql table. Unfortunatelly default option with `dataType = DataType.BIG_DECIMAL_NUMERIC` create just a `DECIMAL(10,0)` which is not usable for my usecase. I was trying to manually set column definition but in that case I get truncation error.

I have written test for that using h2 for quick example

```kotlin
class TestBigDecimalInsert {

    lateinit var connectionSource: JdbcConnectionSource
    val number = BigDecimal("419.7500000000001")
    
    @Before fun setup() {
        connectionSource = JdbcConnectionSource("jdbc:h2:mem:account")
    }

    @Test fun doInsert() {
        val dao = DaoManager.createDao(connectionSource, Entity::class.java)

        TableUtils.createTable(dao)

        assertEquals(0, dao.countOf())

        val entity = Entity(0L, number)
        dao.create(entity)

        assertEquals(1L, dao.countOf())
    }

    @DatabaseTable
    class Entity(
        @DatabaseField(generatedId = true)
        var id: Long = 0L,

        @DatabaseField(dataType = DataType.BIG_DECIMAL_NUMERIC, canBeNull = false, columnDefinition = "DECIMAL(10,10) NOT NULL")
//        @DatabaseField(dataType = DataType.BIG_DECIMAL_NUMERIC, canBeNull = false)
        var spent: BigDecimal = BigDecimal("0.0")
    )
}
```

it throws

```

java.sql.SQLException: Unable to run insert stmt on object datasource.TestBigDecimalInsert$Entity@23a5fd2: INSERT INTO `entity` (`spent` ) VALUES (?)

	at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:25)
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:137)
	at com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:458)
	at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:328)
	at datasource.TestBigDecimalInsert.doInsert(bigdecimal-insert.kt:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "SPENT DECIMAL(10, 10) NOT NULL": "419.7500000000 (13)"; SQL statement:
INSERT INTO `entity` (`spent` ) VALUES (?) [22001-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:369)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:793)
	at org.h2.command.dml.Insert.insertRows(Insert.java:151)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:164)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:150)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:183)
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
	... 26 more

```

What is the right approach to persist `BigDecimal` as a numbers in database using ormlight?

Thank you!

**Comment by j256** [comment]
Sorry I can't grok your test.  Can you make it java7 compliant?  Thanks much.

**Comment by ruXlab** [comment]
Sorry, here is a java version:


```
import com.j256.ormlite.dao.Dao;
import com.j256.ormlite.dao.DaoManager;
import com.j256.ormlite.field.DataType;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.jdbc.JdbcConnectionSource;
import com.j256.ormlite.table.DatabaseTable;
import com.j256.ormlite.table.TableUtils;
import org.junit.Before;
import org.junit.Test;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

import static org.junit.Assert.assertEquals;


public class BigDecimalInsertTest {

    JdbcConnectionSource connectionSource;
    BigDecimal number = new BigDecimal("419.7500000000001");

    @Before
    public void setup() throws SQLException {
        connectionSource = new JdbcConnectionSource("jdbc:h2:mem:account");
    }

    @Test
    public void doInsert() throws SQLException {
        Dao<Entity, Long> dao = DaoManager.createDao(connectionSource, Entity.class);

        TableUtils.createTable(dao);

        assertEquals(0, dao.countOf());

        Entity entity = new Entity(0L, number);
        dao.create(entity);

        assertEquals(1L, dao.countOf());
    }

    @DatabaseTable
    public static class Entity {
        @DatabaseField(generatedId = true)
        Long id = 0L;

        @DatabaseField(dataType = DataType.BIG_DECIMAL_NUMERIC, canBeNull = false, columnDefinition = "DECIMAL(10,10) NOT NULL")
        //        @DatabaseField(dataType = DataType.BIG_DECIMAL_NUMERIC, canBeNull = false)
        BigDecimal spent = new BigDecimal("0.0");

        public Entity() {
        }

        public Entity(Long id, BigDecimal spent) {
            this.id = id;
            this.spent = spent;
        }
    }
}

```

I'm having exactly the same error, thanks!

**Comment by j256** [comment]
Sorry, I don't see this as a bug.  You are specifically defining the field as `DECIMAL(10,10)` which limits the value stored in the DB to 10 digits of precision.  If you remove that custom declaration, your test works for me.  See: http://www.h2database.com/html/datatypes.html#decimal_type
