### ISSUE TITLE
SQLException when testing the project

### ISSUE THREAD

**Issue by Gu-Youngfeng** [j256/ormlite-core#122]
I do nothing about the project, and just install it on my computer using **_mvn compile_**, it success, then I want to test it by using **_mvn test_**, and it failed, the whole test suite cannot move and the test cases all have the similar errors like this, `No suitable driver`, but I have already installed mysql database and configurated some jdbc connection, why would this errors happen?  Looking for your help ...

> testQueryAll(com.j256.ormlite.dao.ReferenceObjectCacheTest)  Time elapsed: 0 sec  <<< ERROR!
java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:278)
	at com.j256.ormlite.h2.H2DatabaseType.<init>(H2DatabaseType.java:20)
	at com.j256.ormlite.h2.H2ConnectionSource.<init>(H2ConnectionSource.java:20)
	at com.j256.ormlite.h2.H2ConnectionSource.<init>(H2ConnectionSource.java:26)
	at com.j256.ormlite.BaseCoreTest.before(BaseCoreTest.java:28)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

So, the test suite is failed, the whole 1960 tests failed 1802.

> Tests run: 1960, Failures: 0, Errors: 1802, Skipped: 0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.320 s
[INFO] Finished at: 2017-11-08T11:22:29+08:00
[INFO] Final Memory: 16M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project ormlite-core: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/yongfeng/workspace/ormlite_parent/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by Gu-Youngfeng** [comment]
Maybe this error will give some insights on installation simplicity :)

**Comment by Gu-Youngfeng** [comment]
Maybe I should run this project on Windows?

**Comment by j256** [comment]
Huh.  No idea why this would be happening.  By default ormlite-core uses H2 for its tests.  Is this the first test that is run or do all of the tests fail in this way.

**Comment by Gu-Youngfeng** [comment]
Through the **pom.xml**, I know the project need the dependency of `h2`, but Maven can automatic download the dependency jar from the remote repository and add it into the classpath, so why do this happen?

Another interesting things is when I deploy the project on `Linux` it fails, but it runs well on `Windows`, so I wonder whether my `Windows` operation has `h2` in system path?

Looking for your help :)

**Comment by j256** [comment]
Sorry, I just really don't understand this.  Again I just tested this under Linux (Red Hat Enterprise Linux Server release 7.3 (Maipo)) and it worked fine.  This is from a fresh repo.
