### ISSUE TITLE
Could not compile this SELECT statement since the caller is expecting a SELECT statement

### ISSUE THREAD

**Issue by andyken** [j256/ormlite-core#126]
Throwable occurred: java.sql.SQLException: Could not compile this SELECT statement since the caller is expecting a SELECT statement.  Check your QueryBuilder methods.
	at com.j256.ormlite.stmt.mapped.MappedPreparedStmt.compile(MappedPreparedStmt.java:52)
	at com.j256.ormlite.stmt.mapped.MappedPreparedStmt.compile(MappedPreparedStmt.java:45)
	at com.j256.ormlite.stmt.StatementExecutor.queryForFirst(StatementExecutor.java:102)
	at com.j256.ormlite.dao.BaseDaoImpl.queryForFirst(BaseDaoImpl.java:239)
	at com.j256.ormlite.stmt.QueryBuilder.queryForFirst(QueryBuilder.java:380)
	at com.j256.ormlite.stmt.Where.queryForFirst(Where.java:494)

**Comment by j256** [comment]
Wow.  That's a crazy error.  Check out the code:

		if (this.type != type) {
			throw new SQLException("Could not compile this " + this.type + " statement since the caller is expecting a "
					+ type + " statement.  Check your QueryBuilder methods.");
		}

That exception is only printed if the type is not equal.  Can you debug to that line and see what is going on?

**Comment by j256** [comment]
I'm going to close this.  Feel free to re-open if you have more info.
