### ISSUE TITLE
ormlite 5.1: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode

### ISSUE THREAD

**Issue by denisk20** [j256/ormlite-core#140]
I have a set of espresso android tests where at the beginning of each test I create a new `OrmLiteSqliteOpenHelper`. After the test is finished I close the helper and drop the database using `android.content.Context#deleteDatabase`. After upgrading to 5.1 I started to see the following error when running the whole suite (individual tests pass fine):

```
android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:634)
at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:320)
at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:294)
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:652)
at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:289)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
at com.j256.ormlite.android.AndroidConnectionSource.getReadWriteConnection(AndroidConnectionSource.java:68)
... 19 more
```

After I switch back to 5.0 everything works fine.

Any ideas of what has changed between 5.0 and 5.1 that might be causing this? In release notes I see

`Added synchronized keyword to BaseDaoImpl.createOrUpdate() and createIfNotExists().`

not sure if it's relevant..

**Comment by ankushg** [comment]
Running into the same issue -- did you end up figuring this out?

**Comment by denisk20** [comment]
No, I have never upgraded since then((

**Comment by j256** [comment]
Sorry for the delayed response.  For the record we did fix some issues with the transaction manager's connection and savepoint handling in 5.2 and 5.3 that might have affected this. 

If anyone has a set of tests that reproduce this I'd be happy to take a look.
