### ISSUE TITLE
Stracktrace-Error

### ISSUE THREAD

**Issue by lichtamberg** [j256/ormlite-core#142]
Hi,

we are getting quite frequently following error, which is only displayed in debug log level:

```
05-24 13:24:35.627 V/SQLiteCursor: Cursor open object=52072473
    java.lang.Throwable: stacktrace
        at android.database.sqlite.SQLiteCursor.<init>(SQLiteCursor.java:117)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:50)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1346)
        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1285)
        at com.j256.ormlite.android.compat.JellyBeanApiCompatibility.rawQuery(JellyBeanApiCompatibility.java:21)
        at com.j256.ormlite.android.AndroidCompiledStatement.getCursor(AndroidCompiledStatement.java:193)
        at com.j256.ormlite.android.AndroidCompiledStatement.runQuery(AndroidCompiledStatement.java:72)
        at com.j256.ormlite.stmt.StatementExecutor.queryForFirst(StatementExecutor.java:106)
        at com.j256.ormlite.dao.BaseDaoImpl.queryForFirst(BaseDaoImpl.java:240)
```

Do you have any hints? There are no cursor leaks afaik, so I'm really not sure why I see this message so often. This also happens when I start my app completely clean and don't do much sql writing/reading work...?

**Comment by j256** [comment]
Is this really the full exception or is there a caused-by information?

**Comment by lichtamberg** [comment]
This is really unfortunately the full exception, there is no more information showing up. The strange thing is also, that this error is only shown in verbose-logging and hidden in higher log levels..

**Comment by j256** [comment]
Ouch.  Is it possible this is after the application has closed but is not fully down and part of it comes up thinking it is has valid database connections?  I'm really not an Android programmer although I play one on TV so I'm not going to be much help.  Maybe posting that stack on SO?

**Comment by lichtamberg** [comment]
I've posted this error on SO too: https://stackoverflow.com/questions/50875210/ormlite-stacktrace-error-without-further-log-entries

**Comment by j256** [comment]
Any chance you are trying to do database operations _before_ the database is open somehow?

**Comment by lichtamberg** [comment]
I have another stacktrace now, not sure if it helps:

```
10-23 16:02:49.093 D/SQLiteDatabase: Open database
    java.lang.Throwable: stacktrace
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:815)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:576)
        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:269)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
        at com.j256.ormlite.android.AndroidConnectionSource.getReadWriteConnection(AndroidConnectionSource.java:68)
        at com.j256.ormlite.android.AndroidConnectionSource.getReadOnlyConnection(AndroidConnectionSource.java:55)
        at com.j256.ormlite.dao.BaseDaoImpl.queryForFirst(BaseDaoImpl.java:238)
```

**Comment by noordawod** [comment]
Would it be possible to have a minimal viable app where you can replicate this behaviour? The stack trace gives away nothing that can help trace this bug.
