### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method updateColumnValue

### ISSUE THREAD

**Issue by vungocduy1261993** [j256/ormlite-core#143]
ATAL EXCEPTION: main
                  Process: com.ezgmo.cube, PID: 16275
                  java.lang.NoSuchMethodError: No virtual method updateColumnValue(Ljava/lang/String;Ljava/lang/Object;)Lcom/j256/ormlite/stmt/StatementBuilder; in class Lcom/j256/ormlite/stmt/UpdateBuilder; or its super classes (declaration of 'com.j256.ormlite.stmt.UpdateBuilder' appears in /data/app/com.ezgmo.cube-1/base.apk:classes14.dex)
                      at jp.mfapps.lib.payment.common.db.model.PaymentStateModel.updateColumns(PaymentStateModel.java:31)
                      at jp.mfapps.lib.payment.common.db.model.PaymentStateModel.updateColumns(PaymentStateModel.java:24)
                      at jp.mfapps.lib.payment.common.db.model.EntityModel$1.run(EntityModel.java:51)
                      at jp.mfapps.lib.payment.common.db.model.EntityModel$1.run(EntityModel.java:46)
                      at jp.mfapps.lib.payment.common.db.model.EntityModel.run(EntityModel.java:183)
                      at jp.mfapps.lib.payment.common.db.model.EntityModel.update(EntityModel.java:46)
                      at jp.mfapps.lib.payment.common.db.model.EntityModel.insertOrUpdate(EntityModel.java:38)
                      at jp.mfapps.lib.payment.v3.task.PaymentTask.logState(PaymentTask.java:344)
                      at jp.mfapps.lib.payment.v3.task.PurchaseStatusApiTask.checkPurchaseStatus(PurchaseStatusApiTask.java:68)
                      at jp.mfapps.lib.payment.v3.task.ConsumeTask.stepYPurchaseStatusCheck(ConsumeTask.java:339)
                      at jp.mfapps.lib.payment.v3.task.ConsumeTask.onStepXCheckListFinished(ConsumeTask.java:263)
                      at jp.mfapps.lib.payment.v3.task.ConsumeTask$2.onQueryInventoryFinished(ConsumeTask.java:232)
                      at jp.mfapps.lib.payment.v3.IabHelper$2$1.run(IabHelper.java:677)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:7409)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by j256** [comment]
Any chance you are using proguard?

**Comment by julis** [comment]
Hi, I get the same problem. Is there any update on this ?

**Comment by j256** [comment]
Nope.  You using proguard @lulis?

**Comment by davidbcn** [comment]
I just got the same crash in release builds only.

**Comment by j256** [comment]
Looks like you are mismatching maybe the core and android ORMlite versions.  They need to be symmetric.
