### ISSUE TITLE
ConnectionSource DaoManager Memory Cleanup

### ISSUE THREAD

**Issue by bosborn** [j256/ormlite-core#150]
This issue comes from ngageoint/geopackage-java#43

The DaoManager builds a class map using ConnectionSource/Class pairs.  Currently the [only way to clean up](https://github.com/j256/ormlite-core/blob/20cf75e51467892a12c091a9213c493c1787922b/src/main/java/com/j256/ormlite/dao/DaoManager.java#L178) this memory on a per ConnectionSource basis appears to be:

`public static synchronized void unregisterDao(ConnectionSource connectionSource, Dao<?, ?> dao)`

Each newly opened ConnectionSource builds a new set of cached class mappings.  Over time when connections are continually opened and closed, the memory continues to grow.

Would like to clear the cache for a single closed ConnectionSource without having to clear the entire cache (for other open connections).  This is requiring [checking for initialized DAOs from all known types](https://github.com/ngageoint/geopackage-core-java/blob/0872e17308a5b43827992814fbcd48e08d6419cf/src/main/java/mil/nga/geopackage/db/GeoPackageDaoManager.java#L43).

Adding the following test to [DaoManagerTest](https://github.com/j256/ormlite-core/blob/master/src/test/java/com/j256/ormlite/dao/DaoManagerTest.java) demonstrates this:
```
@Test
public void testMemory() throws Exception {
	System.out.println((Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory()) / Math.pow(1024, 2) + " MB");
	for (int i = 1; i < Integer.MAX_VALUE; i++) {
		Dao<Bar, Void> dao = DaoManager.createDao(connectionSource, Bar.class);
		assertNotNull(dao);
		connectionSource.closeQuietly();
		if(i % 500000 == 0){
			System.out.println("Connections: " + i + ", " + (Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory()) / Math.pow(1024, 2) + " MB");
		}
		//DaoManager.unregisterDaos(connectionSource);
		connectionSource = new WrappedConnectionSource(new H2ConnectionSource());
	}
}
```

```
10.240394592285156 MB
Connections: 500000, 1488.419075012207 MB
Connections: 1000000, 2782.03369140625 MB
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
	at java.lang.StringBuilder.<init>(StringBuilder.java:89)
	at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:248)
	at sun.net.www.protocol.file.Handler.parseURL(Handler.java:67)
	at java.net.URL.<init>(URL.java:615)
	at java.net.URL.<init>(URL.java:483)
	at sun.misc.URLClassPath$FileLoader.getResource(URLClassPath.java:1058)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:199)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:364)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
```

Pull request #149 maintains the initialized DAO classes for each connection source and adds the ability to unregister an entire ConnectionSource.

With the pull request,uncommenting this line in the test fixes the issue:
`DaoManager.unregisterDaos(connectionSource);`

```
10.24041748046875 MB
Connections: 500000, 39.68568420410156 MB
Connections: 1000000, 24.738937377929688 MB
Connections: 1500000, 18.499404907226562 MB
Connections: 2000000, 85.73055267333984 MB
Connections: 2500000, 17.07880401611328 MB
Connections: 3000000, 22.4501953125 MB
Connections: 3500000, 17.299232482910156 MB
Connections: 4000000, 17.567947387695312 MB
Connections: 4500000, 21.799285888671875 MB
Connections: 5000000, 50.238922119140625 MB
Connections: 5500000, 42.639183044433594 MB
Connections: 6000000, 19.88774871826172 MB
Connections: 6500000, 10.036582946777344 MB
Connections: 7000000, 24.818809509277344 MB
Connections: 7500000, 33.16831970214844 MB
Connections: 8000000, 41.17674255371094 MB
Connections: 8500000, 65.35406494140625 MB
Connections: 9000000, 12.500190734863281 MB
Connections: 9500000, 9.166419982910156 MB
Connections: 10000000, 25.78905487060547 MB
```

A nice step further would be to clear the cache when each ConnectionSource ([JdbcConnectionSource](https://github.com/j256/ormlite-jdbc/blob/master/src/main/java/com/j256/ormlite/jdbc/JdbcConnectionSource.java), [AndroidConnectionSource](https://github.com/j256/ormlite-android/blob/master/src/main/java/com/j256/ormlite/android/AndroidConnectionSource.java), etc) is closed.  For the test, adding this call to [WrappedConnectionSource close](https://github.com/j256/ormlite-core/blob/20cf75e51467892a12c091a9213c493c1787922b/src/test/java/com/j256/ormlite/WrappedConnectionSource.java#L74) accomplishes this.

```
@Override
public void close() throws IOException {
	DaoManager.unregisterDaos(this);
	// …
}
```

**Comment by bosborn** [comment]
`DaoManager.unregisterDaos(ConnectionSource connectionSource)` merged in #149
