### ISSUE TITLE
Investigating odd stack trace from TableInfo.getFieldTypeByColumnName()

### ISSUE THREAD

**Issue by dlew** [j256/ormlite-core#229]
I'm a little lost trying to figure out the root cause, figured maybe you'd have some idea...

We're running ORMLite on Android, and a few times a day, we're seeing a call to `TableInfo.getFieldTypeByColumnName()` fail in a seemingly impossible manner:

```
Caused by java.lang.IllegalArgumentException: You should use columnName 'name' for table organizations instead of fieldName 'name'
       at com.j256.ormlite.table.TableInfo.getFieldTypeByColumnName(TableInfo.java:168)
       at com.j256.ormlite.stmt.StatementBuilder.verifyColumnName(StatementBuilder.java:195)
       at com.j256.ormlite.stmt.QueryBuilder.addSelectColumnToList(QueryBuilder.java:662)
       at com.j256.ormlite.stmt.QueryBuilder.selectColumns(QueryBuilder.java:117)
```

I'm not sure how you can end up in this state. Based on [my reading of `getFieldTypeByColumnName()`](https://github.com/j256/ormlite-core/blob/master/src/main/java/com/j256/ormlite/table/TableInfo.java#L147-L172), it essentially:

1. Creates a `Map<ColumnName, FieldType>` for the table.
2. Tries to return the `FieldType` that matches the provided `ColumnName`.
3. If it fails, it tries to figure out if maybe you provided a `FieldName` instead of a `ColumnName`.

That all seems reasonable to me; however, **in the stack trace it shows the same `FieldName` and `ColumnName`**. If the error-checking for-loop can find the right `FieldType`, then why doesn't the `Map<ColumnName, FieldType>` have it?

---------

We get this crash only intermittently, not consistently, so it's not something fundamentally wrong with the calling code. **I suspect some sort of concurrency issue, though I don't see anything obviously wrong here.** It could be something with [the oddities of SMP on Android](https://developer.android.com/training/articles/smp). Perhaps the `Map` creation needs to be synchronized?

We've know we've seen this since ORMLite 5.3, though it's possible we saw it earlier than that (it's just that our crash logs don't go back that far).

Any ideas on how this could happen?

**Comment by dlew** [comment]
> The message is definitively screwed up but I think that it's saying the name isn't in the field list. 

How could it not be, if it can point to a `FieldType` that has the exact name it was searching for?

> Could this be a synchronization thing?

That's what I thought, and it could still be that, but:

1. There's no modification to the map after creation, so if you have a reference to a map, it's essentially immutable.
2. I tried throwing a concurrency test its way and couldn't get it to crash. (Perhaps my test was bad though.)

> One thing that I could do is spit out the fields in the object in the future but that doesn't help you now.

FYI, this is not anything particularly urgent on our end, so if adding some extra debugging would help, I'm for it.

**Comment by dlew** [comment]
Supposing this is an extremely rare concurrency issue due to Android threading, would you be open to either:

1. Making `fieldNameMap` volatile.
2. Initializing `fieldNameMap` in the constructor.

I'm partial to constructor initialization because it rules out an entire class of issues (concurrency), though I don't know how important this optimization is to performance.

I can put up a PR for either, just don't want to do that w/o your approval.

**Comment by j256** [comment]
Sure thing @dlew .  No good reason to not put it in the constructor.  File a PR and I'll submit the code against it.

**Comment by j256** [comment]
Thanks.  Happy to have your PR and name on the submission as long as you don't mind me tweaking it after.  :-)
