### ISSUE TITLE
createTableIfNotExists fails when using indexes with MariaDB

### ISSUE THREAD

**Issue by BluemediaGER** [j256/ormlite-core#251]
Hi,
first of all thank you for this great project. ormlite has become my favorite ORM for smaller projects.

I am currently struggling with the problem that `TableUtils.createTableIfNotExists()` fails when indexes are defined by an annotation in a class. The first creation of the tables still works, but the next call of the function (e.g. after a application restart) fails because it tries to create the already existing indexes again.

```
java.sql.SQLException: SQL statement failed: CREATE UNIQUE INDEX `users_username_idx` ON `users` ( `username` )
	at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:25)
	at com.j256.ormlite.table.TableUtils.doStatements(TableUtils.java:396)
	at com.j256.ormlite.table.TableUtils.doCreateTable(TableUtils.java:372)
	at com.j256.ormlite.table.TableUtils.doCreateTable(TableUtils.java:357)
	at com.j256.ormlite.table.TableUtils.createTableIfNotExists(TableUtils.java:75)
```

I'm able to reproduce the problem with the following software versions:
- MariaDB 10.6.5
- mariadb-java-client 2.7.4
- ormlite-core 5.7
- ormlite-jdbc 5.7

**Comment by BluemediaGER** [comment]
The underlying seems to reside in ormlite-jdbc. I have created the issue j256/ormlite-jdbc#71 there which is why I am closing this one here.
