### ISSUE TITLE
writeConfigFile() generates Enum name with $ sign

### ISSUE THREAD

**Issue by jahd2602** [j256/ormlite-core#28]
writeConfigFile() generates Enum name with $ sign using [this Enum code](http://pastebin.com/mgifbj6V). Produces the following error:
```
 Caused by: java.lang.IllegalArgumentException: Invalid class is not an Enum for unknownEnumValue: com.jahd.omdmovil.modelo.Color$1#NINGUNO
            at com.j256.ormlite.field.DatabaseFieldConfigLoader.readField(DatabaseFieldConfigLoader.java:335)
            at com.j256.ormlite.field.DatabaseFieldConfigLoader.fromReader(DatabaseFieldConfigLoader.java:54)
            at com.j256.ormlite.table.DatabaseTableConfigLoader.readFields(DatabaseTableConfigLoader.java:163)
            at com.j256.ormlite.table.DatabaseTableConfigLoader.fromReader(DatabaseTableConfigLoader.java:65)
            at com.j256.ormlite.table.DatabaseTableConfigLoader.loadDatabaseConfigFromReader(DatabaseTableConfigLoader.java:32)
            at com.j256.ormlite.android.apptools.OrmLiteSqliteOpenHelper.<init>(OrmLiteSqliteOpenHelper.java:85)
            at com.j256.ormlite.android.apptools.OrmLiteSqliteOpenHelper.<init>(OrmLiteSqliteOpenHelper.java:54)
            at com.jahd.omdmovil.OrmHelper.<init>(OrmHelper.java:54)
```
Investigated and it occurs because in the config file, the problematic line is: 
```
unknownEnumValue=com.jahd.omdmovil.modelo.Color$1#NINGUNO
```
And when *com.jahd.omdmovil.modelo.Color$1* is passed to:
```java
			try {
				enumClass = Class.forName(parts[0]);
			} catch (ClassNotFoundException e) {
				throw new IllegalArgumentException("Unknown class specified for unknownEnumValue: " + value);
			}
			Object[] consts = enumClass.getEnumConstants();
```
the consts array is null. The workaround was replacing the problematic string with:
```
unknownEnumValue=com.jahd.omdmovil.modelo.Color#NINGUNO
```
Notice the missing dollar sign. However I don't know if it's better to fix the writeConfigFile() method, or the readField() method.

**Comment by j256** [comment]
Thanks for this.  Sorry for such a delayed response.  I've finally got some tests of this but can't reproduce it.  Any chance you can boil this down to a unit test for me to reproduce?  See: https://github.com/j256/ormlite-core/blob/59092cecd492f45aa056c94e14748bd98ac30343/src/test/java/com/j256/ormlite/field/DatabaseFieldConfigLoaderTest.java#L282

**Comment by j256** [comment]
AHA!  Just after I posted this I figured it out.  The difference is that your enum's are anonymous classes.  Ok, I've got a valid test.  Let me poke at it.

**Comment by j256** [comment]
Ok wow, that was easy.   Fixed it.  I didn't know about `Enum.getDeclaringClass()`.   See: https://github.com/j256/ormlite-core/commit/7b26e5d9d35942513f9168a731ba7479598d6432
