### ISSUE TITLE
'not implemented by SQLite JDBC driver' error with the driver org.xerial.sqlite-jdbc 3.43.0.0 

### ISSUE THREAD

**Issue by zonex5** [j256/ormlite-core#288]
Related to the latest changes: https://github.com/xerial/sqlite-jdbc/issues/329

Exception in thread "main" java.sql.SQLException: Unable to run insert stmt on object Category(id=0, name=John): INSERT INTO `category` (`name` ) VALUES (?)
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:139)
	at com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:464)
	at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:337)
	at com.j256.ormlite.dao.BaseDaoImpl.createIfNotExists(BaseDaoImpl.java:381)
	at xyz.toway.tools.Main.main(Main.java:9)
Caused by: java.sql.SQLFeatureNotSupportedException: not implemented by SQLite JDBC driver
	at org.sqlite.jdbc3.JDBC3PreparedStatement.unsupported(JDBC3PreparedStatement.java:448)
	at org.sqlite.jdbc3.JDBC3Statement.getGeneratedKeys(JDBC3Statement.java:357)
	at com.j256.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:188)
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
	... 4 more

**Comment by sproket** [comment]
Thanks I created this bug as well. PITA. This breaks my library tests. I'll have to stick with an older version for my tests and have a note about this in my release notes.

**Comment by j256** [comment]
Sorry for this @sproket .  What's the fix?  Upgrade to a later version of the xerial?

**Comment by sproket** [comment]
No it's Persism https://github.com/sproket/Persism - I was using getGeneratedKeys prior since some DBs don't support RETURNING clause. It's fine though. I updated the library to use the returning method to get the auto-inc back and it's working. I'm going to put up a new release soon. Thanks!

**Comment by Phoenix616** [comment]
This should be solved by https://github.com/sjlombardo/sqlite-jdbc/commit/3bebfdac80daadb78bd7eba22ef5bd3266b0cf6c (in 3.44.1.1-SNAPSHOT)

**Comment by Phoenix616** [comment]
Solved now in xerial sqlite jdbc with https://github.com/xerial/sqlite-jdbc/releases/tag/3.45.0.0
