### ISSUE TITLE
Problem parsing with field defined as DataType.DATE_LONG

### ISSUE THREAD

**Issue by vladaman** [j256/ormlite-core#302]
@j256  Using ormlite 5.7 on Android I am suddenly experiencing new issue. I am not sure why it started with no upgrades.

```
    implementation('com.j256.ormlite:ormlite-android:5.7')
    implementation('com.j256.ormlite:ormlite-jdbc:5.7')
```

Error:
```
java.sql.SQLException: Problems with field FieldType:name=dateCreated,class=EReceptHistoryItemModel parsing 
  default date-string '0' using 'yyyy-MM-dd HH:mm:ss.SSSSSS'
  at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:27)
  at com.j256.ormlite.field.types.DateStringType.parseDefaultString(DateStringType.java:47)
  at com.j256.ormlite.field.FieldType.assignDataType(FieldType.java:1195)
  at com.j256.ormlite.field.FieldType.<init>(FieldType.java:294)
```

Field Definition:
```java
@DatabaseField(columnName = "date_created", dataType = DataType.DATE_LONG, canBeNull = false, defaultValue = "0")
private java.util.Date dateCreated = new Date(0);
```

There is also interesting behaviour when creating table:
1. When definition is DATE_LONG and default value is date string (which IMHO is incorrect), I get an error `Problems with field FieldType:name=dateCreated,class=EReceptHistoryModel parsing default date-long value: 1970-01-01 00:00:00`

```
@DatabaseField(columnName = "date_created", dataType = DataType.DATE_LONG, defaultValue = "1970-01-01 00:00:00", canBeNull = false)
```

2. Changing default value to "0" throws: `Problems with field FieldType:name=dateCreated,class=EReceptHistoryModel parsing default date-string '0' using 'yyyy-MM-dd HH:mm:ss.SSSSSS'`

```
@DatabaseField(columnName = "date_created", dataType = DataType.DATE_LONG, defaultValue = "0", canBeNull = false)
```

Why just changing default value from 0 to '1970..' affects the way we parse default value?

**Comment by vladaman** [comment]
OK I figured where was the issue. We have extended another class which had different datetype serialization applied to it.
