### ISSUE TITLE
DateTimeType isn't valid for version

### ISSUE THREAD

**Issue by outofrange** [j256/ormlite-core#47]
Hi!
I'm currently using ormlite 4.48 and saw that it's not possible to use a `org.joda.time.DateTime` object as a version.

    @DatabaseField(version = true)
    private DateTime modified;

will lead to

    Caused by: java.lang.IllegalArgumentException: Field modified is not a valid type to be a version field
    	at com.j256.ormlite.field.FieldType.<init>(FieldType.java:267)
    	at com.j256.ormlite.field.FieldType.createFieldType(FieldType.java:957)
    	at com.j256.ormlite.table.DatabaseTableConfig.extractFieldTypes(DatabaseTableConfig.java:208)
    	at com.j256.ormlite.table.DatabaseTableConfig.fromClass(DatabaseTableConfig.java:146)
    	at com.j256.ormlite.table.TableInfo.<init>(TableInfo.java:53)
    	at com.j256.ormlite.dao.BaseDaoImpl.initialize(BaseDaoImpl.java:151)
    	at com.j256.ormlite.dao.BaseDaoImpl.<init>(BaseDaoImpl.java:128)
    	at com.j256.ormlite.dao.BaseDaoImpl.<init>(BaseDaoImpl.java:107)
    	at org.obehave.persistence.impl.SubjectDaoImpl.<init>(SubjectDaoImpl.java:15)
    	... 41 more

Is this intentional?
If not, and if it's as simple as overriding `isValidForVersion()` and `moveToNextValue(Object)` as done in `BaseDateType`, I would be happy to try that and create a pull request.

**Comment by j256** [comment]
Good point.  Just added to trunk.  Will be in 4.49.  Thanks!  See: https://github.com/j256/ormlite-core/commit/23e82deedbae23fc9cdbd64ecb77d6585723a30b
