### ISSUE TITLE
No fields have a DatabaseField annotation in class 

### ISSUE THREAD

**Issue by toniton** [j256/ormlite-core#51]
04-10 12:30:15.175  19820-19820/com.diaryinc.diaryoffice E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.diaryinc.diaryoffice, PID: 19820
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.diaryinc.diaryoffice/com.diaryinc.diaryoffice.SplashActivity}: java.lang.IllegalArgumentException: No fields have a DatabaseField annotation in class com.diaryinc.diaryoffice.database.entities.SimpleDataContract
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2394)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2452)
            at android.app.ActivityThread.access$900(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1302)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5586)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalArgumentException: No fields have a DatabaseField annotation in class com.diaryinc.diaryoffice.database.entities.SimpleDataContract
            at com.j256.ormlite.table.DatabaseTableConfig.extractFieldTypes(DatabaseTableConfig.java:215)
            at com.j256.ormlite.table.DatabaseTableConfig.fromClass(DatabaseTableConfig.java:146)
            at com.j256.ormlite.table.TableInfo.<init>(TableInfo.java:53)
            at com.j256.ormlite.dao.BaseDaoImpl.initialize(BaseDaoImpl.java:151)
            at com.j256.ormlite.dao.BaseDaoImpl.<init>(BaseDaoImpl.java:128)
            at com.j256.ormlite.dao.BaseDaoImpl.<init>(BaseDaoImpl.java:107)
            at com.j256.ormlite.dao.BaseDaoImpl$4.<init>(BaseDaoImpl.java:907)
            at com.j256.ormlite.dao.BaseDaoImpl.createDao(BaseDaoImpl.java:907)
            at com.j256.ormlite.dao.DaoManager.createDao(DaoManager.java:70)
            at com.j256.ormlite.table.TableUtils.createTable(TableUtils.java:218)
            at com.j256.ormlite.table.TableUtils.createTable(TableUtils.java:53)
            at com.diaryinc.diaryoffice.database.helpers.DatabaseHelper.createTable(DatabaseHelper.java:54)
            at com.diaryinc.diaryoffice.database.helpers.DatabaseHelper.onCreate(DatabaseHelper.java:35)
            at com.j256.ormlite.android.apptools.OrmLiteSqliteOpenHelper.onCreate(OrmLiteSqliteOpenHelper.java:209)
            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
            at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
            at com.j256.ormlite.android.AndroidConnectionSource.getReadWriteConnection(AndroidConnectionSource.java:66)
            at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:308)
            at com.diaryinc.diaryoffice.SplashActivity.doSampleDatabaseStuff(SplashActivity.java:48)
            at com.diaryinc.diaryoffice.SplashActivity.onCreate(SplashActivity.java:29)
            at android.app.Activity.performCreate(Activity.java:5451)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2452)
            at android.app.ActivityThread.access$900(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1302)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5586)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by outofrange** [comment]
Do your fields have a DatabaseField annotation in class?

**Comment by toniton** [comment]
I got it fixed already. I was automating a lot of things, that's why.

-----Original Message-----

**Comment by j256** [comment]
I think this can be closed right?
