### ISSUE TITLE
JPA @IdClass annotation support

### ISSUE THREAD

**Issue by nikolaikopernik** [j256/ormlite-core#52]
Class:
```
@IdClass(value = TProductPK.class)
@Entity
@Table(name = "t_product")
public class TProduct {
   
    @Id
    @Column(name = "markingOfTheGood")
    private String code;

    @Id
    @Column(name = "status")
    private int status = 0;
...
}
```

JPA specification says:
>The IdClass annotation is applied to an entity class or a mapped superclass to specify a composite
primary key class that is mapped to multiple fields or properties of the entity
>Example:
```
>@IdClass(com.acme.EmployeePK.class)
>@Entity
>public class Employee {
>@Id String empName;
>@Id Date birthDay;
>...
>}
```

But I have:
```
java.sql.SQLException: More than 1 idField configured for class class ru.crystals.pos.datasource.jdbc.example.TProduct (FieldType:name=markingOfTheGood,class=TProduct,FieldType:name=status,class=TProduct)
	at com.j256.ormlite.table.TableInfo.<init>(TableInfo.java:80)
	at com.j256.ormlite.table.TableInfo.<init>(TableInfo.java:53)
	at com.j256.ormlite.dao.BaseDaoImpl.initialize(BaseDaoImpl.java:151)
	at com.j256.ormlite.dao.BaseDaoImpl.<init>(BaseDaoImpl.java:128)
	at com.j256.ormlite.dao.BaseDaoImpl.<init>(BaseDaoImpl.java:107)
	at com.j256.ormlite.dao.BaseDaoImpl$4.<init>(BaseDaoImpl.java:907)
	at com.j256.ormlite.dao.BaseDaoImpl.createDao(BaseDaoImpl.java:907)
	at com.j256.ormlite.dao.DaoManager.createDao(DaoManager.java:70)
	at com.j256.ormlite.field.FieldType.configDaoInformation(FieldType.java:341)
	at com.j256.ormlite.dao.BaseDaoImpl.initialize(BaseDaoImpl.java:201)
	at com.j256.ormlite.dao.BaseDaoImpl.<init>(BaseDaoImpl.java:128)
	at com.j256.ormlite.dao.BaseDaoImpl.<init>(BaseDaoImpl.java:107)
	at com.j256.ormlite.dao.BaseDaoImpl$4.<init>(BaseDaoImpl.java:907)
	at com.j256.ormlite.dao.BaseDaoImpl.createDao(BaseDaoImpl.java:907)
	at com.j256.ormlite.dao.DaoManager.createDao(DaoManager.java:70)
```

**Comment by j256** [comment]
Unfortunately, to support an id class right now is hard for the code.  I can't see that I will be supporting it any time soon.  Feel free to propose a solution if you have one.
